site_name: Hirte Documentation

repo_url: https://github.com/containers/hirte
repo_name: hirte

copyright: © Red Hat
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - DBus API: 
    - Description: api/description.md
    - Examples: api/examples.md
  - Proxy Services: 
    - Concept: proxy/concept.md

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: True
  - sane_lists
  - smarty
  - admonition
  - pymdownx.snippets

base_path: doc
